# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'ZhiBo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZhiBo
    pod 'Alamofire', '~> 3.1.2'
    pod 'Kingfisher','~> 2.1.0'
end
